### ISSUE TITLE
It is very unclear what I'm meant to do with ffmpeg

### ISSUE THREAD

**Issue by Victinitotodilepro** [MrMendelli/yt-dlp-CLI#3]
I've downloaded ffmpeg from pretty much every link in the official website by now, most of those didn't have a bin file or folder, which is what I was instructed to extract into the yt-dlp folder. The few which had a bin folder had 3 executables inside, I tried placing these 3 in the previously mentioned folder but the bat file doesn't seem to recognize them. I've tried placing all kinds of files in there but nothing seems to work. What is it that I should place and where should I place those files?, I'm really confused, thank you in advance btw.

**Comment by MrMendelli** [comment]
If ffmpeg is not found my script will direct you to the official downloads page [here](https://ffmpeg.org/download.html#build-windows/). Either host from the downloads page will work. Your folder for ffmpeg should be a subdirectory as seen below:
![image](https://github.com/user-attachments/assets/347c00b0-3eab-4e8b-91ea-78851a1349cc)
```
C:\Programs\Media\Video\Ripping\yt-dlp
|   7z.dll
|   cookies.txt
|   GitHub (yt-dlp CLI).url
|   GitHub (yt-dlp).url
|   GitHub (ytdlp-interface).url
|   Help.txt
|   readme.md
|   Repo.lnk
|   Supported Sites.md
|   yt-dlp CLI.bat
|   ytdlp-interface.exe
|   ytdlp-interface.json
|   
+---ffmpeg
|       ffmpeg.exe
|       ffprobe.exe
|       
\---yt-dlp
    |   GitHub.url
    |   yt-dlp.conf
    \---yt-dlp.exe
```

**Comment by lovelydumpling** [comment]
Well, that explains my own issues. Your folder structure here has ffmpeg in its own folder, 
but the download didn't come with an ffmpeg subfolder, 
and your instructions in the CLI asks the user to put the ffmpeg exes in the _yt-dlp_ subfolder, 
and then still says ffmpeg is not installed.
Creating an ffmpeg subfolder and putting them there worked.

**Comment by MrMendelli** [comment]
Thank you for the report, I have issued a bugfix:
https://github.com/MrMendelli/yt-dlp-CLI/commit/4be58c826de42b9f3d06fabaedfcb14f8f895ac5
